// src/menuData.ts

/** GitHub Pages(예: /menu/)에서도 public 파일이 깨지지 않게 base를 자동 반영 */
const publicUrl = (p: string) => `${import.meta.env.BASE_URL}${p.replace(/^\/+/, "")}`;

export type Category =
  | "All"
  | "BEEF BBQ"
  | "PORK BBQ"
  | "LIVE"
  | "OTHER BBQ"
  | "HOTPOT"
  | "STEW"
  | "CHEESE SERIES"
  | "SIDEDISH"
  | "RICE"
  | "NOODLES"
  | "BEVERAGES";


export const categories: Category[] = [
  "All",
  "BEEF BBQ",
  "PORK BBQ",
  "LIVE",
  "OTHER BBQ",
  "HOTPOT",
  "STEW",
  "CHEESE SERIES",
  "SIDEDISH",
  "RICE",
  "NOODLES",
  "BEVERAGES",
];


export type Price =
  | { kind: "fixed"; rm: number }
  | { kind: "market" };

export type Tag = "Best" | "Spicy" | "SOJU" | "BEER" | "WINE" | "SOFT DRINKS" | "RECOMMENDED";

export type Item = {
  id: string;
  name: string;
  nameKo?: string;    // KO (optional)
  desc?: string;
  category: Exclude<Category, "All">;
  tags?: Tag[];
  image: { src: string; alt: string };
  price: Price;
};

export const items: Item[] = [
  //BEEF BBQ  
  {
    id: "beef-bbq-1",
    category: "BEEF BBQ",
    nameKo: "갈비본살",
    name: "GALBI BONSAL",
    desc: "Boneless short ribs",
    tags: ["Best", "RECOMMENDED"],
    image: { src: publicUrl("menu/beef/galbi-bonsal.webp"), alt: "GALBI BONSAL" },
    price: { kind: "market" },
  },
  {
    id: "beef-bbq-2",
    category: "BEEF BBQ",
    nameKo: "생갈비",
    name: "SAENG GALBI",
    desc: "Bone-in short ribs",
    image: { src: publicUrl("menu/beef/saeng-galbi.webp"), alt: "SAENG GALBI" },
    price: { kind: "market" },
  },
  {
    id: "beef-bbq-3",
    category: "BEEF BBQ",
    nameKo: "양념갈비",
    name: "YANGNYEOM GALBI",
    desc: "Short ribs marinated in soy sauce",
    image: { src: publicUrl("menu/beef/yangnyeom-galbi.webp"), alt: "YANGNYEOM GALBI" },
    price: { kind: "market" },
  },
  {
    id: "beef-bbq-4",
    category: "BEEF BBQ",
    nameKo: "우설구이",
    name: "WOOSEUL GUI",
    desc: "Beef tongue",
    image: { src: publicUrl("menu/beef/wooseul-gui.webp"), alt: "WOOSEUL GUI" },
    price: { kind: "market" },
  },
  {
    id: "beef-bbq-5",
    category: "BEEF BBQ",
    nameKo: "우삼겹",
    name: "WOOSEUL GUI",
    desc: "Thinly sliced, richly marbled beef",
    image: { src: publicUrl("menu/beef/woosamgyeop.webp"), alt: "WOOSEUL GUI" },
    price: { kind: "market" },
  },

  //PORK BBQ
  {
    id: "pork-bbq-1",
    category: "PORK BBQ",
    nameKo: "항정살",
    name: "HANGJUNGSAL",
    desc: "Pork belly",
    tags: ["Best"],
    image: { src: publicUrl("menu/pork/hangjungsal.webp"), alt: "HANGJUNGSAL" },
    price: { kind: "market" },
  },
  {
    id: "pork-bbq-2",
    category: "PORK BBQ",
    nameKo: "삼겹살",
    name: "SAMGYEOPSAL",
    desc: "Pork belly",
    image: { src: publicUrl("menu/pork/samgyeopsal.webp"), alt: "SAMGYEOPSAL" },
    price: { kind: "market" },
  },
  {
    id: "pork-bbq-3",
    category: "PORK BBQ",
    nameKo: "목살",
    name: "MOKSAL",
    desc: "Pork shoulder",
    image: { src: publicUrl("menu/pork/moksal.webp"), alt: "MOKSAL" },
    price: { kind: "market" },
  },
  {
    id: "pork-bbq-4",
    category: "PORK BBQ",
    nameKo: "꽃삼겹살",
    name: "KKOT SAMGYEOPSAL",
    desc: "Thinly sliced pork belly",
    image: { src: publicUrl("menu/pork/kkot-samgyeopsal.webp"), alt: "KKOT SAMGYEOPSAL" },
    price: { kind: "market" },
  },
  {
    id: "pork-bbq-5",
    category: "PORK BBQ",
    nameKo: "고추장삼겹살",
    name: "GOCHUJANG SAMGYEOPSAL",
    desc: "Pork belly marinated in spicy chili paste",
    image: { src: publicUrl("menu/pork/gochujang-samgyeopsal.webp"), alt: "GOCHUJANG SAMGYEOPSAL" },
    price: { kind: "market" },
  },
  {
    id: "pork-bbq-6",
    category: "PORK BBQ",
    nameKo: "양념 돼지갈비",
    name: "YANGNYEOM DWAEJIGALBI",
    desc: "Pork marinated in soy sauce",
    image: { src: publicUrl("menu/pork/yangnyeom-dwaejigalbi.webp"), alt: "YANGNYEOM DWAEJI GALBI" },
    price: { kind: "market" },
  },

  //LIVE
  {
    id: "live-1",
    category: "LIVE",
    nameKo: "생 블랙타이거 새우찜",
    name: "LIVE BLACK TIGER PRAWN JJIM",
    desc: "Steamed live black tiger prawns",
    tags: ["Best"],
    image: { src: publicUrl("menu/live/live-black-tiger-prawns.webp"), alt: "LIVE BLACK TIGER PRAWN JJIM" },
    price: { kind: "market" },
  },

  //OTHER BBQ
  {
    id: "other-bbq-1",
    category: "OTHER BBQ",
    nameKo: "양갈비",
    name: "YANG GALBI",
    desc: "Lamb rack",
    image: { src: publicUrl("menu/other/yang-galbi.webp"), alt: "YANG GALBI" },
    price: { kind: "market" },
  },
  {
    id: "other-bbq-2",
    category: "OTHER BBQ",
    nameKo: "닭갈비",
    name: "DAK GALBI",
    desc: "Chicken marinated in spicy chili sauce",
    image: { src: publicUrl("menu/other/dak-galbi.webp"), alt: "DAK GALBI" },
    price: { kind: "market" },
  },
  {
    id: "other-bbq-3",
    category: "OTHER BBQ",
    nameKo: "양념 닭갈비",
    name: "YANGNYEOM DAK GALBI",
    desc: "Chicken marinated in soy sauce",
    image: { src: publicUrl("menu/other/yangnyeom-dak-galbi.webp"), alt: "YANGNYEOM DAK GALBI" },
    price: { kind: "market" },
  },
  {
    id: "other-bbq-4",
    category: "OTHER BBQ",
    nameKo: "양념 주꾸미",
    name: "YANGNYEOM JUKKUMI",
    desc: "webfoot octopus marinated in spicy chili sauce",
    image: { src: publicUrl("menu/other/yangnyeom-jukkumi.webp"), alt: "YANGNYEOM JUKKUMI" },
    price: { kind: "market" },
  },

  //HOTPOT
  {
    id: "hotpot-1",
    category: "HOTPOT",
    nameKo: "돼지전골",
    name: "DWAEJI JEONGOL",
    desc: "5 different pork parts hot pot",
    image: { src: publicUrl("menu/hotpot/dwaeji-jeongol.webp"), alt: "DWAEJI JEONGOL" },
    price: { kind: "fixed", rm: 75 },
  },
  {
    id: "hotpot-2",
    category: "HOTPOT",
    nameKo: "소꼬리전골",
    name: "SOKKORI JEONGOL",
    desc: "Oxtail and beef bone hot pot",
    image: { src: publicUrl("menu/hotpot/sokkori-jeongol.webp"), alt: "SOKKORI JEONGOL" },
    price: { kind: "fixed", rm: 110 },
  },
  {
    id: "hotpot-3",
    category: "HOTPOT",
    nameKo: "김치찜",
    name: "KIMCHI JJIM",
    desc: "Aged kimchi hotpot\nwith pork belly and ribs.",
    image: { src: publicUrl("menu/hotpot/kimchi-jjim.webp"), alt: "KIMCHI JJIM" },
    price: { kind: "fixed", rm: 95 },
  },
  {
    id: "hotpot-4",
    category: "HOTPOT",
    nameKo: "김치전골",
    name: "KIMCHI JEONGOL",
    desc: "Spicy hot pot with kimchi, pork,tofu, rice cake and sari (ramen noodles)",
    image: { src: publicUrl("menu/hotpot/kimchi-jeongol.webp"), alt: "KIMCHI JEONGOL" },
    price: { kind: "fixed", rm: 80 },
  },
  {
    id: "hotpot-5",
    category: "HOTPOT",
    nameKo: "부대전골",
    name: "BUDAE JEONGOL",
    desc: "Bone broth stew with ham, sausage, baked beans, vegetables and sari (ramen noodles)",
    image: { src: publicUrl("menu/hotpot/budae-jeongol.webp"), alt: "BUDAE JEONGOL" },
    price: { kind: "fixed", rm: 90 },
  },
  {
    id: "hotpot-6",
    category: "HOTPOT",
    nameKo: "갈비찜",
    name: "GALBI JJIM",
    desc: "Braised short ribs hotpot and vegetables in soy sauce stew",
    image: { src: publicUrl("menu/hotpot/galbi-jjim.webp"), alt: "GALBI JJIM" },
    price: { kind: "fixed", rm: 95 },
  },
  //STEW
  {
    id: "stew-1",
    category: "STEW",
    nameKo: "돼지국밥",
    name: "DWAEJI GUKBAP",
    desc: "Pork soup",
    tags: ["Best", "RECOMMENDED"],
    image: { src: publicUrl("menu/stew/dwaeji-gukbap.webp"), alt: "DWAEJI GUKBAP" },
    price: { kind: "fixed", rm: 27 },
  },
  {
    id: "stew-2",
    category: "STEW",
    nameKo: "소꼬리탕",
    name: "SOKKORI TANG",
    desc: "Oxtail and beef bone soup",
    tags: ["RECOMMENDED"],
    image: { src: publicUrl("menu/stew/sokkori-tang.webp"), alt: "SOKKORI TANG" },
    price: { kind: "fixed", rm: 45 },
  },
  {
    id: "stew-3",
    category: "STEW",
    nameKo: "김치찌개",
    name: "KIMCHI JJIGAE",
    desc: "Spicy stew made\nwith kimchi, pork, vegetables and tofu",
    image: { src: publicUrl("menu/stew/kimchi-jjigae.webp"), alt: "KIMCHI JJIGAE" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "stew-4",
    category: "STEW",
    nameKo: "순두부찌개",
    name: "SUNDUBU JJIGAE",
    desc: "Soft tofu simmered in a spicy broth with pork and vegetables",
    image: { src: publicUrl("menu/stew/sundubu-jjigae.webp"), alt: "SUNDUBU JJIGAE" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "stew-5",
    category: "STEW",
    nameKo: "해물 순두부찌개",
    name: "HAEMUL SUNDUBU JJIGAE",
    desc: "Soft tofu simmered in a spicy broth with seafood and vegetables",
    image: { src: publicUrl("menu/stew/haemul-sundubu-jjigae.webp"), alt: "HAEMUL SUNDUBU JJIGAE" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "stew-6",
    category: "STEW",
    nameKo: "해물 된장찌개",
    name: "HAEMUL DOENJANG JJIGAE",
    desc: "Soybean paste-based stew with seafood, vegetables and tofu",
    image: { src: publicUrl("menu/stew/haemul-doenjang-jjigae.webp"), alt: "HAEMUL DOENJANG JJIGAE" },
    price: { kind: "fixed", rm: 27 },
  },
  {
    id: "stew-7",
    category: "STEW",
    nameKo: "소고기 된장찌개",
    name: "SOGOGI DOENJANG JJIGAE",
    desc: "Soybean paste-based stew with beef, vegetables and tofu",
    image: { src: publicUrl("menu/stew/sogogi-doenjang-jjigae.webp"), alt: "SOGOGI DOENJANG JJIGAE" },
    price: { kind: "fixed", rm: 27 },
  },
  {
    id: "stew-8",
    category: "STEW",
    nameKo: "소 불고기",
    name: "SO BULGOGI",
    desc: "Soy sauce-based stew with beef, vegetables mushrooms and glass noodles",
    image: { src: publicUrl("menu/stew/bulgogi.webp"), alt: "SO BULGOGI" },
    price: { kind: "fixed", rm: 45 },
  },
  {
    id: "stew-9",
    category: "STEW",
    nameKo: "돼지 불고기",
    name: "DWAEJI BULGOGI",
    desc: "Soy sauce-based stew with pork, vegetables mushrooms and glass noodles",
    image: { src: publicUrl("menu/stew/bulgogi.webp"), alt: "DWAEJI BULGOGI" },
    price: { kind: "fixed", rm: 40 },
  },
  {
    id: "stew-10",
    category: "STEW",
    nameKo: "갈비탕",
    name: "GALBI TANG",
    desc: "Beef rib broth with radish and glass noodles",
    image: { src: publicUrl("menu/stew/galbi-tang.webp"), alt: "GALBI TANG" },
    price: { kind: "fixed", rm: 40 },
  },
  //CHEESE SERIES
  {
    id: "cheese-1",
    category: "CHEESE SERIES",
    nameKo: "치즈 닭갈비",
    name: "CHEESE DAK GALBI",
    desc: "Chicken marinated in spicy chili paste with mozzarella cheese",
    image: { src: publicUrl("menu/cheese/cheese-dak-galbi.webp"), alt: "CHEESE DAK GALBI" },
    price: { kind: "fixed", rm: 80 },
  },
  {
    id: "cheese-2",
    category: "CHEESE SERIES",
    nameKo: "고구마무스 닭갈비",
    name: "GOGUMA MOUSSE DAK GALBI",
    desc: "Chicken marinated in spicy chili paste with sweet potato mousse",
    image: { src: publicUrl("menu/cheese/goguma-mousse-dak-galbi.webp"), alt: "GOGUMA MOUSSE DAK GALBI" },
    price: { kind: "fixed", rm: 80 },
  },
  {
    id: "cheese-3",
    category: "CHEESE SERIES",
    nameKo: "치즈 제육볶음",
    name: "CHEESE JEYUKBOKKEUM",
    desc: "Sliced stir-fried pork belly marinated in spicy chili paste with mozzarella cheese",
    image: { src: publicUrl("menu/cheese/cheese-jeyukbokkeum.webp"), alt: "CHEESE JEYUKBOKKEUM" },
    price: { kind: "fixed", rm: 80 },
  },
  {
    id: "cheese-4",
    category: "CHEESE SERIES",
    nameKo: "치즈 주꾸미",
    name: "CHEESE JUKKUMI",
    desc: "Webfoot octopus marinated in spicy chili paste with mozzarella cheese",
    image: { src: publicUrl("menu/cheese/cheese-jukkumi.webp"), alt: "CHEESE JUKKUMI" },
    price: { kind: "fixed", rm: 80 },
  },
  {
    id: "cheese-5",
    category: "CHEESE SERIES",
    nameKo: "치즈 떡볶이",
    name: "CHEESE TTEOKBOKKI",
    desc: "Korean rice cakes and fish cake stir-fried in hot spicy chili sauce with mozzarella cheese",
    image: { src: publicUrl("menu/cheese/cheese-tteokbokki.webp"), alt: "CHEESE TTEOKBOKKI" },
    price: { kind: "fixed", rm: 60 },
  },
  //SIDEDISH
  {
    id: "side-1",
    category: "SIDEDISH",
    nameKo: "부추전",
    name: "BUCHU JEON",
    desc: "Chive pancake",
    image: { src: publicUrl("menu/side/buchu-jeon.webp"), alt: "BUCHU JEON" },
    price: { kind: "fixed", rm: 15 },
  },
  {
    id: "side-2",
    category: "SIDEDISH",
    nameKo: "해물파전",
    name: "HAEMUL PAJEON",
    desc: "Seafood pancake topped with spring onions",
    image: { src: publicUrl("menu/side/haemul-pajeon.webp"), alt: "HAEMUL PAJEON" },
    price: { kind: "fixed", rm: 20 },
  },
  {
    id: "side-3",
    category: "SIDEDISH",
    nameKo: "김치전",
    name: "KIMCHI JEON",
    desc: "Kimchi pancake",
    image: { src: publicUrl("menu/side/kimchi-jeon.webp"), alt: "KIMCHI JEON" },
    price: { kind: "fixed", rm: 15 },
  },
  {
    id: "side-4",
    category: "SIDEDISH",
    nameKo: "녹두전",
    name: "NOKDU JEON",
    desc: "Ground mung bean pancake",
    image: { src: publicUrl("menu/side/nokdu-jeon.webp"), alt: "NOKDU JEON" },
    price: { kind: "fixed", rm: 15 },
  },
  {
    id: "side-5",
    category: "SIDEDISH",
    nameKo: "계란찜",
    name: "GYERAN JJIM",
    desc: "Steamed eggs",
    image: { src: publicUrl("menu/side/gyeran-jjim.webp"), alt: "GYERAN JJIM" },
    price: { kind: "fixed", rm: 10 },
  },
  {
    id: "side-6",
    category: "SIDEDISH",
    nameKo: "떡볶이",
    name: "TTEOKBOKKI",
    desc: "Stir-fried Korean rice cakes and fish cake in hot spicy chili sauce",
    image: { src: publicUrl("menu/side/tteok-bokki.webp"), alt: "TTEOKBOKKI" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "side-7",
    category: "SIDEDISH",
    nameKo: "낙지 소면",
    name: "NAKJI SOMYEON",
    desc: "Stir-fried small octopus in spicy chili sauce with noodles",
    image: { src: publicUrl("menu/side/nakji-somyeon.webp"), alt: "NAKJI SOMYEON" },
    price: { kind: "fixed", rm: 70 },
  },
  {
    id: "side-8",
    category: "SIDEDISH",
    nameKo: "오징어 소면",
    name: "OJINUH SOMYEON",
    desc: "Stir-fried squid in spicy chili sauce with noodles",
    image: { src: publicUrl("menu/side/nakji-somyeon.webp"), alt: "OJINUH SOMYEON" },
    price: { kind: "fixed", rm: 70 },
  },
  {
    id: "side-9",
    category: "SIDEDISH",
    nameKo: "육회",
    name: "YUK HOE",
    desc: "Fresh thinly sliced raw beef seasoned with soy sauce, sesame oil, garlic, and pear",
    image: { src: publicUrl("menu/side/yuk-hoe.webp"), alt: "YUK HOE" },
    price: { kind: "fixed", rm: 70 },
  },
  {
    id: "side-10",
    category: "SIDEDISH",
    nameKo: "두부 김치",
    name: "DUBU KIMCHI",
    desc: "Tofu and stir-fried kimchi",
    image: { src: publicUrl("menu/side/dubu-kimchi.webp"), alt: "DUBU KIMCHI" },
    price: { kind: "fixed", rm: 60 },
  },
  {
    id: "side-11",
    category: "SIDEDISH",
    nameKo: "보쌈",
    name: "BOSSAM",
    desc: "Boiled pork with oyster kimchi",
    image: { src: publicUrl("menu/side/bossam.webp"), alt: "BOSSAM" },
    price: { kind: "fixed", rm: 60 },
  },
  {
    id: "side-12",
    category: "SIDEDISH",
    nameKo: "마늘 보쌈",
    name: "MANEUL BOSSAM",
    desc: "Boiled pork topped with sweet garlic sauce",
    image: { src: publicUrl("menu/side/maneul-bossam.webp"), alt: "MANEUL BOSSAM" },
    price: { kind: "fixed", rm: 65 },
  },
  {
    id: "side-13",
    category: "SIDEDISH",
    nameKo: "제육볶음",
    name: "JEYUK BOKKEUM",
    desc: "Sliced pork belly stir-fried and marinated in spicy chili paste",
    image: { src: publicUrl("menu/side/jeyuk-bokkeum.webp"), alt: "JEYUK BOKKEUM" },
    price: { kind: "fixed", rm: 60 },
  },
  {
    id: "side-14",
    category: "SIDEDISH",
    nameKo: "잡채",
    name: "JAPCHAE",
    desc: "Stir-fried glass noodles with vegetables topped with sesame oil",
    image: { src: publicUrl("menu/side/japchae.webp"), alt: "JAPCHAE" },
    price: { kind: "fixed", rm: 40 },
  },
  //RICE
  {
    id: "rice-1",
    category: "RICE",
    nameKo: "제육 비빔밥",
    name: "JEYUK BIBIMBAP",
    desc: "Rice with spicy chili paste, various vegetables and spicy stir-fried pork in stone pot",
    image: { src: publicUrl("menu/rice/jeyuk-bibimbap.webp"), alt: "JEYUK BIBIMBAP" },
    price: { kind: "fixed", rm: 33 },
  },
  {
    id: "rice-2",
    category: "RICE",
    nameKo: "돌솥 비빔밥",
    name: "DOLSOT BIBIMBAP",
    desc: "Rice with spicy chili paste, various vegetables and a raw egg in stone pot",
    image: { src: publicUrl("menu/rice/dolsot-bibimbap.webp"), alt: "DOLSOT BIBIMBAP" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "rice-3",
    category: "RICE",
    nameKo: "김치 볶음밥",
    name: "KIMCHI BOKKEUMBAP",
    desc: "Kimchi fried rice topped with omelet and seaweed flakes",
    image: { src: publicUrl("menu/rice/kimchi-bokkeumbap.webp"), alt: "KIMCHI BOKKEUMBAP" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "rice-4",
    category: "RICE",
    nameKo: "소불고기 볶음밥",
    name: "SO BULGOGI BOKKEUMBAP",
    desc: "Beef marinated in soy sauce stir-fried with rice",
    image: { src: publicUrl("menu/rice/bulgogi-bokkeumbap.webp"), alt: "SO BULGOGI BOKKEUMBAP" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "rice-5",
    category: "RICE",
    nameKo: "돼지불고기 볶음밥",
    name: "DWAEJI BULGOGI BOKKEUMBAP",
    desc: "Pork marinated in soy sauce stir-fried with rice",
    image: { src: publicUrl("menu/rice/bulgogi-bokkeumbap.webp"), alt: "DWAEJI BULGOGI BOKKEUMBAP" },
    price: { kind: "fixed", rm: 25 },
  },
  {
    id: "rice-6",
    category: "RICE",
    nameKo: "주먹밥",
    name: "JUMEOKBAP",
    desc: "Rice ball made with vegetables and roasted seaweed flakes",
    image: { src: publicUrl("menu/rice/jumeokbap.webp"), alt: "JUMEOKBAP" },
    price: { kind: "fixed", rm: 15 },
  },
  {
    id: "rice-7",
    category: "RICE",
    nameKo: "밥 추가",
    name: "STEAM RICE",
    image: { src: publicUrl("menu/rice/steam-rice.webp"), alt: "STEAM RICE" },
    price: { kind: "fixed", rm: 5 },
  },
  //NOODLES
  {
    id: "noodles-1",
    category: "NOODLES",
    nameKo: "들기름 막국수",
    name: "DEULGIREUM MAKGUKSU",
    desc: "Buckwheat noodles mixed with perilla oil",
    image: { src: publicUrl("menu/noodles/deulgireum-makguksu.webp"), alt: "DEULGIREUM MAKGUKSU" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-2",
    category: "NOODLES",
    nameKo: "물냉면",
    name: "MUL NAENGMYEON",
    desc: "Chilled buckwheat noodles.\nserved in beef broth",
    image: { src: publicUrl("menu/noodles/mul-naengmyeon.webp"), alt: "MUL NAENGMYEON" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-3",
    category: "NOODLES",
    nameKo: "비빔냉면",
    name: "BIBIM NAENGMYEON",
    desc: "Chilled buckwheat noodles mixed.\nin spicy sauce",
    tags: ["Spicy"],
    image: { src: publicUrl("menu/noodles/bibim-naengmyeon.webp"), alt: "BIBIM NAENGMYEON" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-4",
    category: "NOODLES",
    nameKo: "김치말이 국수",
    name: "KIMCHIMARI GUKSU",
    desc: "Cold broth with kimchi and seaweed flakes",
    image: { src: publicUrl("menu/noodles/kimchimari-guksu.webp"), alt: "KIMCHIMARI GUKSU" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-5",
    category: "NOODLES",
    nameKo: "라면",
    name: "RAMYEON",
    desc: "Korean instant noodles with egg",
    image: { src: publicUrl("menu/noodles/ramyeon.webp"), alt: "RAMYEON" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-6",
    category: "NOODLES",
    nameKo: "잔치국수",
    name: "JANCHI GUKSU",
    desc: "Wheat flour noodles in a light anchovy broth",
    image: { src: publicUrl("menu/noodles/janchi-guksu.webp"), alt: "JANCHI GUKSU" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "noodles-7",
    category: "NOODLES",
    nameKo: "산더미국수",
    name: "SANDUHMI GUKSU",
    desc: "Wheat flour noodles in a light anchovy broth topped with mountain like vegetables",
    tags: ["Best", "RECOMMENDED"],
    image: { src: publicUrl("menu/noodles/sanduhmi-guksu.webp"), alt: "SANDUHMI GUKSU" },
    price: { kind: "fixed", rm: 21 },
  },
  //BEVERAGES
  {
    id: "beverages-1",  
    category: "BEVERAGES",
    nameKo: "참이슬",
    name: "CHAMISUL",
    tags: ["SOJU"],
    image: { src: publicUrl("menu/beverages/chamisul.webp"), alt: "CHAMISUL" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-2",  
    category: "BEVERAGES",
    nameKo: "처음처럼",
    name: "CHUMCHURUM",
    tags: ["SOJU"],
    image: { src: publicUrl("menu/beverages/chumchurum.webp"), alt: "CHUMCHURUM" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-3",  
    category: "BEVERAGES",
    nameKo: "새로",
    name: "SAERO",
    tags: ["SOJU"],
    image: { src: publicUrl("menu/beverages/saero.webp"), alt: "SAERO" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-4",  
    category: "BEVERAGES",
    nameKo: "자몽 소주",
    name: "GRAPEFRUIT SOJU",
    tags: ["SOJU"],
    image: { src: publicUrl("menu/beverages/grapefruit-soju.webp"), alt: "GRAPEFRUIT SOJU" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-5",  
    category: "BEVERAGES",
    nameKo: "청포도 소주",
    name: "GREEN GRAPE SOJU",
    tags: ["SOJU"],
    image: { src: publicUrl("menu/beverages/green-grape-soju.webp"), alt: "GREEN GRAPE SOJU" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-6",  
    category: "BEVERAGES",
    nameKo: "타이거 병맥주",
    name: "TIGER(BOTTLE)",
    tags: ["BEER"],
    image: { src: publicUrl("menu/beverages/tiger.webp"), alt: "TIGER" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-7",  
    category: "BEVERAGES",
    nameKo: "한국 병맥주",
    name: "KOREAN BEER(BOTTLE)",
    tags: ["BEER"],
    image: { src: publicUrl("menu/beverages/korean-beer.webp"), alt: "KOREAN BEER(BOTTLE)" },
    price: { kind: "fixed", rm: 30 },
  },
  {
    id: "beverages-8",  
    category: "BEVERAGES",
    nameKo: "막걸리",
    name: "MAKGEOLLI",
    desc: "Korean rice wine",
    tags: ["WINE"],
    image: { src: publicUrl("menu/beverages/maekgeolli.webp"), alt: "MAKGEOLLI" },
    price: { kind: "fixed", rm: 35 },
  },
  {
    id: "beverages-9",  
    category: "BEVERAGES",
    nameKo: "콜라",
    name: "COKE",
    tags: ["SOFT DRINKS"],
    image: { src: publicUrl("menu/beverages/coke.webp"), alt: "COKE" },
    price: { kind: "fixed", rm: 5 },
  },
  {
    id: "beverages-10",  
    category: "BEVERAGES",
    nameKo: "스프라이트",
    name: "SPRITE",
    tags: ["SOFT DRINKS"],
    image: { src: publicUrl("menu/beverages/sprite.webp"), alt: "SPRITE" },
    price: { kind: "fixed", rm: 5 },
  },
  {
    id: "beverages-11",  
    category: "BEVERAGES",
    nameKo: "100 플러스",
    name: "100 PLUS",
    tags: ["SOFT DRINKS"],
    image: { src: publicUrl("menu/beverages/100plus.webp"), alt: "100 PLUS" },
    price: { kind: "fixed", rm: 5 },
  },
  {
    id: "beverages-12",  
    category: "BEVERAGES",
    nameKo: "갈아만든 배",
    name: "GALAMANDEUNBAE",
    desc: "Korean pear juice",
    tags: ["SOFT DRINKS"],
    image: { src: publicUrl("menu/beverages/galamandeunbae.webp"), alt: "GALAMANDEUNBAE" },
    price: { kind: "fixed", rm: 7 },
  }
];
